version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: split_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data

  arangodb:
    image: neo4j:latest
    environment:
      ARANGO_ROOT_PASSWORD: arangopassword
    ports:
      - "8529:8529"
    volumes:
      - arangodata:/var/lib/arangodb3
      - arangologs:/var/lib/arangodb3-apps

  backend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - arangodb

volumes:
  pgdata3:
  arangodata:
  arangologs: