server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/split_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password

security:
  ignored: /api/auth/**
  jwt:
    secret: pfvfdpvpdcjdfucfdkcnshjbchbhcbhjdbschjbsjhrbsdbcbhsjhdbcsbdcjhsdbchdbcbsjbchsjdbchjbsjhcyebchdbsdbchjsdbcsdhjcbsdbcjhsbd
    lifetime: 10000



